'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Car_Project.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _201px_Dodge_logo_svg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("201px-Dodge_logo.svg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4253248173_8277702e01_z() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4253248173_8277702e01_z", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6a0148c7628432970c014e88a08896970d_800wi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6a0148c7628432970c014e88a08896970d-800wi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6a0148c7628432970c014e88a08896970d_800wi1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6a0148c7628432970c014e88a08896970d-800wi1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _these_and_auto_unions_black_white_stream_of_city_lights_wallpaper_b_o_ibackgroundz_com() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("-these-and-auto-unions-black-white-stream-of-city-lights-wallpaper-b-o-ibackgroun"& _ 
                        "dz.com", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property abbey_road15041s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abbey-road15041s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Accord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Accord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Autobahn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Autobahn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property avenger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("avenger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Aveo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aveo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Aveo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aveo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Beetle1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Beetle1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Beetle2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Beetle2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Camero1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Camero1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property challenger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("challenger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property charger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("charger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chev_soni_ext_ph_big_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chev_soni_ext_ph_big_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chev_soni_ext_ph_big_131() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chev_soni_ext_ph_big_131", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ChevyLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChevyLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property city_traffic_lights_in_black_and_white_wide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("city_traffic_lights_in_black_and_white-wide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property city_traffic_lights_in_black_and_white_wide1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("city_traffic_lights_in_black_and_white-wide1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Civic1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Civic1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CR_Z() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CR-Z", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cruze1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cruze1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cruze2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cruze2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DodgeLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DodgeLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property durango() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("durango", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fiesta1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fiesta1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fit1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fit1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Focus1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Focus1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FordLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FordLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fordlogo2003() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fordlogo2003", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fordLogoEn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fordLogoEn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fusion1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fusion1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Golf1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Golf1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property grandcaravan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grandcaravan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property honda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("honda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HondaLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HondaLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HondaLogo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HondaLogo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Inisght() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Inisght", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jetta1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jetta1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_chevrolet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_chevrolet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lrg_newchevrolet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lrg_newchevrolet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lrg_Star_Wars50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lrg_Star_Wars50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mustang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mustang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nights() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nights", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nights_in_light_city_background1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nights-in-light-city-background1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property open_road1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open-road1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property open_road11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open-road11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Passat1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Passat1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pod2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pod2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property road_miller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("road_miller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rotan1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rotan1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property slide2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("slide2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sonic1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sonic1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sonic2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sonic2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property star_wars_1_86239() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_wars_1_86239", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tauras() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tauras", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Volt1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Volt1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Volt2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Volt2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property VWLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VWLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
